### ISSUE TITLE
Error occurred when running GAIL

### ISSUE THREAD

**Issue by haoyu-x** [StanfordVL/robosuite#102]
Hi,
Thanks for sharing this great project!

I'm using GAIfO from tf2rl (https://github.com/keiohta/tf2rl).
I choose state-based obs, OSC-position controller and sawyer robot, robosuite v1.0

program will be interrupted by an Error:

[<pre>20:40:50.382 [INFO] (irl_trainer.py:74) Total Epi:    26 Steps:   13000 Episode Steps:   500 Return:  20.0922 FPS:  9.42
20:41:43.588 [INFO] (irl_trainer.py:74) Total Epi:    27 Steps:   13500 Episode Steps:   500 Return:  21.9982 FPS:  9.40
Traceback (most recent call last):
  File &quot;run_gaifo_robosuite.py&quot;, line 134, in &lt;module&gt;
    trainer()
  File &quot;/home/haoyux/tf2rl-master/tf2rl/experiments/irl_trainer.py&quot;, line 52, in __call__
    next_obs, reward, done, _ = self._env.step(action)
  File &quot;/home/haoyux/tf2rl-master/robosuite/wrappers/gym_wrapper.py&quot;, line 75, in step
    ob_dict, reward, done, info = self.env.step(action)
  File &quot;/home/haoyux/tf2rl-master/robosuite/environments/base.py&quot;, line 225, in step
    self.sim.step()
  File &quot;mujoco_py/mjsim.pyx&quot;, line 126, in mujoco_py.cymj.MjSim.step
  File &quot;mujoco_py/cymj.pyx&quot;, line 115, in mujoco_py.cymj.wrap_mujoco_warning.__exit__
  File &quot;mujoco_py/cymj.pyx&quot;, line 75, in mujoco_py.cymj.c_warning_callback
  File &quot;/home/haoyux/venv/lib/python3.6/site-packages/mujoco_py/builder.py&quot;, line 354, in user_warning_raise_exception
    raise MujocoException(warn + &apos;Check for NaN in simulation.&apos;)
mujoco_py.builder.MujocoException: Unknown warning type Time = 17.3500.Check for NaN in simulation.
</pre>](url)

I'm wondering why this happened.
Thanks!

**Comment by cremebrule** [comment]
Hi,

Glad you're finding a good usage for robosuite. :) Thanks for bringing up this issue. It looks like you're getting NaNs from the mujoco sim -- usually, this is due to high acceleration spikes in the simulation which in turn can be due to multiple factors. On the one hand, a badly trained policy or poorly tuned controller can often cause such instability, though this can also be caused / exacerbated by poorly tuned physical parameters (e.g: inertial values, damping, etc.)

I would recommend trying different robot / controller combinations and seeing which ones cause the NaN error -- isolating the source of what's causing the NaNs will be most helpful in terms of modifying and fixing the problem on your local branch.

The branch you currently have had a lot of bugs with the new grippers and robots that were added, and the majority of these major issues have already been cleaned up since then. Thanks for bringing up this issue -- we've been overhauling our v1.0 branch privately, and will be releasing it officially sometime soon. In the meantime, hopefully these comments help you out with your development and research!

I'm closing this issue for now, but once we release v1.0 officially feel free to open another issue there if your problem persists.
