### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by isk03276** [StanfordVL/robosuite#14]
Hi,
Thank you for providing this benchmarking framework.

I have a couple of inconveniences with using this framework.

First, when rendering via "env.render ()", the rendering screen is turned back on whenever the environment is reset. Is there a solution for this?

Second, a GLFW missing error occurs if the "has_offscreen_render" option is set to true when the "has_render" option is false. If both options are true, the rendering screen will blink.

Thank you.

**Comment by amandlek** [comment]
What exactly do you mean by the rendering screen being turned back on when resetting?

I've seen the GLFW missing error when trying to use on-screen rendering on its own (the fix is to run `export LD_PRELOAD=$LD_PRELOAD:/usr/lib/x86_64-linux-gnu/libGLEW.so:/usr/lib/nvidia-410/libGL.so`, assuming you're on Ubuntu with the nvidia-410 driver) but not when using off-screen rendering. Can you post a more detailed example (code and stacktrace)?

Also, we currently don't have support for using both the `has_renderer` option and `has_offscreen_renderer` option, but it should be a pretty easy fix - let us know if you need this functionality and we can address it.

**Comment by isk03276** [comment]
Thanks,

"rendering screen being turned back on when resetting" means that the mujoco_py (rendering process) is turned off every episode (whenever env.reset () is executed).

**Comment by amandlek** [comment]
Right, this is intentional behavior. We destroy the renderer and create a new one on every environment reset.

**Comment by isk03276** [comment]
If the renderer is turned off and on for every episode, it is difficult to do anything else.
Is there a way not to destroy the renderer?

**Comment by amandlek** [comment]
I don't know what you mean by "it is difficult to do anything else" but you can try modifying the behavior [here](https://github.com/StanfordVL/robosuite/blob/master/robosuite/environments/base.py#L146) to avoid destroying the viewer on every reset and see if that is suitable for your use case.
