### ISSUE TITLE
Replay demos using action doesn't work

### ISSUE THREAD

**Issue by normandipalo** [StanfordVL/robosuite#37]
I'm trying to replay some demos in various tasks and environments. While they work setting use-actions to False, they always fail setting it to True.
Is there a solution? Is it caused by some source of non-determinism?

**Comment by amandlek** [comment]
Are you sure you're on the latest commit? I just verified that it works for me by collecting a demonstration and playing it back using the actions.

**Comment by normandipalo** [comment]
I’m sorry, I omitted a detail: I’m referring to the set of demonstrations included in the repo at this link http://cvgl.stanford.edu/projects/roboturk/RoboTurkPilot.zip. 
Where they collected using a different implementation?
I wanted to use those since they are in great quantity instead of re-collecting demos.

**Comment by amandlek** [comment]
Unfortunately, those demonstrations were collected before we had the functionality for deterministic action replay, so exact playback using the collected actions will not work.

**Comment by YeeCY** [comment]
Which version of this repo should I use if I want to replay demonstrations in the RoboTurk dataset via action control?

**Comment by amandlek** [comment]
As mentioned in the comments above, replaying the actions directly will not work, but the data itself can still be used for both online and offline policy learning - the [original paper](https://arxiv.org/abs/1811.02790) uses the demonstration data as resets for doing reinforcement learning (e.g. using [this](https://github.com/StanfordVL/robosuite/blob/master/robosuite/wrappers/demo_sampler_wrapper.py)) and [this paper](https://arxiv.org/abs/1911.05321) learns offline using the actions from the data. You should be on the master branch in order to make sure environment dynamics are consistent with the dataset.

**Comment by YeeCY** [comment]
> As mentioned in the comments above, replaying the actions directly will not work, but the data itself can still be used for both online and offline policy learning - the [original paper](https://arxiv.org/abs/1811.02790) uses the demonstration data as resets for doing reinforcement learning (e.g. using [this](https://github.com/StanfordVL/robosuite/blob/master/robosuite/wrappers/demo_sampler_wrapper.py)) and [this paper](https://arxiv.org/abs/1911.05321) learns offline using the actions from the data. You should be on the master branch in order to make sure environment dynamics are consistent with the dataset.

Thanks, got it.
