### ISSUE TITLE
Velocity actuator gain values on the sawyer too low?

### ISSUE THREAD

**Issue by eugval** [StanfordVL/robosuite#50]
Hello,

Thanks again for the repo, it has been really helpful! :)

Could you please provide some information on how did you decide on the velocity actuator gains for the sawyer, as well as the control ranges for both the velocity and torque versions of the sawyer?

I have setup a pushing task of a small cubic object (5cm edges, 200grams) on the table arena, and am noticing that if the friction of the object is high enough (0.8-0.9) , the sawyer fails to provide enough torque to push the object.

This is fixed if I increase the values of the velocity actuator gains, but I would like to better understand if this is a sensible thing to do, and how to get a good idea of what are sensible gains.

I would also like to create a PID controller on top of mujoco torque actuators by modifying the base, sawyer_robot and sawyer modules, but I am struggling to figure out a way to get sensible P and I gains for each joint.

I would appreciate any insights you could give me on this!

**Comment by cremebrule** [comment]
Apologies for not getting to this sooner. We've actually overhauled our controllers, and will be including PID control for our newest implementation of joint velocity controller. You're welcome to try out the new controllers when we release robosuite v1.0.

In terms of PID tuning, since the robots (assuming you have gravity compensation built in) are relatively stable systems, the classic [Ziegler-Nichols method](https://en.wikipedia.org/wiki/Ziegler%E2%80%93Nichols_method) may be a good starting point for tuning the gains for your purposes.

I will close this issue for now, as this isn't really a specific issue about robosuite, but feel free open up another issue if you run into any problems with the repo.
