### ISSUE TITLE
Weird rotary behavior introduced on the v1.0 branch

### ISSUE THREAD

**Issue by gal-leibovich** [StanfordVL/robosuite#93]
Commit 47bf286 has some parts in it which causes some weird rotary behaviour for Franka Panda with Lift and IK_Pose controller. I haven't tested other combinations, it might be present in there as well.

Running `robosuite/demo_random_action.py`, while selecting `Lift`, `Panda` and `IK_POSE` on the 1.0 branch will exhibit that rotary behavior that I'm seeing. Undoing the relevant parts of commit 47bf286d, which are in the attached patch (`git apply diff.txt`), will return the behavior to be normal as before. 

I'm not really sure why did this change caused this behavior.

[diff.txt](https://github.com/StanfordVL/robosuite/files/4758711/diff.txt)

**Comment by cremebrule** [comment]
thanks for catching these bugs. This was due to an earlier bug in which there was a discrepancy between the controller end effector point of reference and the observation end effector reference. Standardizing this value resulted in the the controller's eef frame of reference changing, leading to the unstable behavior you noted for Panda specifically, which has a rotational offset between its arm and gripper body.

Fixed by integrating this offset into the rotational offset value for Panda. IK has always given us the most trouble so please don't hesitate to continue raising issues!

**Comment by gal-leibovich** [comment]
Hi @cremebrule, thanks a lot for fixing this issue!

I would be happy to continue raising issues if I find ones. Unfortunately, it seems like someone has deleted the v1.0 branch? :-(
